name: Lint Flight Plans

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint Flight Plans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y aspell libaspell-dev aspell-en
          bundle install --without development

      - name: Run lint-flight-plans
        run: ./bin/lint-flight-plans
