name: Build and Release

on:
  push:
    tags:
      - '**'

jobs:
  run-script-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install font
        run: |
          sudo apt-get install -y --no-install-recommends fontconfig

          # Add Source Sans Pro font
          # Adpated from https://gist.github.com/jacksonpradolima/840b4a20c617204a65b15da61e124bf6
          # The RUN <<EOF set -e ... EOF has the effect of chaining all the commands together, so that if one fails, the whole RUN
          # command fails, but only one layer is created.
          set -e
          
          cd $(mktemp -d)
          TEMP_DIR=$(pwd)
          
          wget https://github.com/adobe-fonts/source-sans-pro/archive/2.020R-ro/1.075R-it.zip
          unzip 1.075R-it.zip
          sudo cp source-sans-2.020R-ro-1.075R-it/OTF/*.otf /usr/local/share/fonts
          
          sudo fc-cache -f -v
          rm -rf $TEMP_DIR

      # Install typst to allow for the generation of the PDFs outputs
      - uses: typst-community/setup-typst@v3

      - name: Install dependencies
        run: |
          bundle install --without development

      - name: Lint flight plans
        run: bin/lint-flight-plans

      - name: Create path-safe tag name
        run: echo "SAFE_TAG_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Make release artifacts
        run: bin/make-release ${{ env.SAFE_TAG_NAME }}

      - name: ZIP JSON outputs
        run: zip -r json-outputs-${{ env.SAFE_TAG_NAME }}.zip json-outputs-${{ env.SAFE_TAG_NAME }}

      - name: ZIP PDF outputs
        run: zip -r pdf-outputs-${{ env.SAFE_TAG_NAME }}.zip pdf-outputs-${{ env.SAFE_TAG_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            json-outputs-${{ env.SAFE_TAG_NAME }}.zip
            pdf-outputs-${{ env.SAFE_TAG_NAME }}.zip
