name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  run-script-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Make release artifacts
        run: bin/make-release

      - name: ZIP JSON outputs
        run: zip -r json-outputs.zip json-outputs

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            json-outputs.zip
